"""audit log + is_superuser

Revision ID: 0b622c047ec4
Revises: 756ca49235dd
Create Date: 2026-04-24 13:45:23.760982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b622c047ec4'
down_revision: Union[str, None] = '756ca49235dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('audit_logs_action_idx', ['action'], unique=False)
        batch_op.create_index('audit_logs_actor_idx', ['actor_user_id'], unique=False)
        batch_op.create_index('audit_logs_created_at_idx', ['created_at'], unique=False)

    # Existing rows get is_superuser=false by default. Every new row
    # explicitly sets the flag, so the server_default is transitional.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_superuser', sa.Boolean(),
            nullable=False, server_default=sa.false(),
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('audit_logs_created_at_idx')
        batch_op.drop_index('audit_logs_actor_idx')
        batch_op.drop_index('audit_logs_action_idx')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
