"""subscriptions table

Revision ID: 6e9162270864
Revises: 0b622c047ec4
Create Date: 2026-04-24 14:17:36.971119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9162270864'
down_revision: Union[str, None] = '0b622c047ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('mollie_customer_id', sa.String(length=64), nullable=True),
    sa.Column('mollie_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('current_period_start', sa.String(length=32), nullable=True),
    sa.Column('current_period_end', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
