"""scan job lifecycle columns

Revision ID: 756ca49235dd
Revises: a1bcf39db357
Create Date: 2026-04-24 11:05:28.677548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756ca49235dd'
down_revision: Union[str, None] = 'a1bcf39db357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `status` is NOT NULL with a server_default of 'done' so any rows
    # inserted before Phase 3 (sync-mode scans with a complete payload)
    # are backfilled at migration time. New rows explicitly set a status,
    # so the default is purely transitional.
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'status', sa.String(length=16),
            nullable=False, server_default='done',
        ))
        batch_op.add_column(sa.Column('started_at', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))
        batch_op.create_index('scans_status_idx', ['status'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('scans_status_idx')
        batch_op.drop_column('error')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
