"""users orgs memberships + scan tenant

Revision ID: a1bcf39db357
Revises: 31d8c3af11cc
Create Date: 2026-04-24 03:43:49.951438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bcf39db357'
down_revision: Union[str, None] = '31d8c3af11cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='memberships_user_org_uq')
    )
    op.create_index('memberships_org_idx', 'memberships', ['organization_id'], unique=False)
    op.create_index('memberships_user_idx', 'memberships', ['user_id'], unique=False)
    # SQLite has no ALTER for constraints, so the FK addition has to happen
    # inside batch_alter_table (copy + recreate). Postgres handles the same
    # block fine — batch mode is a no-op there.
    with op.batch_alter_table('scans') as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(length=32), nullable=True))
        batch_op.create_index('scans_org_idx', ['organization_id'], unique=False)
        batch_op.create_foreign_key(
            'scans_organization_id_fkey',
            'organizations', ['organization_id'], ['id'],
            ondelete='CASCADE',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans') as batch_op:
        batch_op.drop_constraint('scans_organization_id_fkey', type_='foreignkey')
        batch_op.drop_index('scans_org_idx')
        batch_op.drop_column('organization_id')
    op.drop_index('memberships_user_idx', table_name='memberships')
    op.drop_index('memberships_org_idx', table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
